# Generated by Django 3.1.5 on 2021-07-28 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=20)),
                ('department_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mould',
            fields=[
                ('mould_id', models.IntegerField(primary_key=True, serialize=False)),
                ('mould_name', models.CharField(max_length=200)),
                ('cavity_number', models.IntegerField()),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('general_maintaince_cleaning_threshold_value', models.IntegerField()),
                ('preventive_maintaince_clearning_thresold_value', models.IntegerField()),
                ('tool_life', models.IntegerField()),
                ('present_count', models.IntegerField()),
                ('moud_desc', models.CharField(max_length=100)),
                ('order_number', models.CharField(max_length=100)),
                ('raw_material', models.CharField(max_length=100)),
                ('part_weight', models.FloatField()),
                ('runner_weight', models.FloatField()),
                ('tonnage', models.FloatField()),
                ('cycle_time', models.FloatField()),
                ('number_of_shots_per_day', models.IntegerField()),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line_number', models.IntegerField()),
                ('product_line_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MouldStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_update', models.DateTimeField(auto_now_add=True)),
                ('count_increment', models.IntegerField()),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_status', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('department_name', models.CharField(max_length=100)),
                ('product_line', models.CharField(max_length=100)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_data', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='MouldComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('commented_date_time', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_user', to=settings.AUTH_USER_MODEL)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_chat', to='mould.mould')),
            ],
        ),
    ]
