# Generated by Django 3.1.5 on 2021-07-28 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralClearningPresent',
            fields=[
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mould_cleaning', serialize=False, to='mould.mould')),
                ('date_applied_for_cleaning', models.DateTimeField(auto_now_add=True)),
                ('date_get_back_from_cleaning', models.DateTimeField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.RemoveField(
            model_name='moulddata',
            name='mould_id',
        ),
        migrations.DeleteModel(
            name='ProductLine',
        ),
        migrations.DeleteModel(
            name='MouldData',
        ),
    ]
