# Generated by Django 3.1.5 on 2021-07-29 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0002_auto_20210729_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralCleaningPresent',
            fields=[
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='mould_cleaning', serialize=False, to='mould.mould')),
                ('date_applied_for_cleaning', models.DateTimeField(auto_now_add=True)),
                ('date_get_back_from_cleaning', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='GeneralClearningPresent',
        ),
    ]
