# Generated by Django 3.1.5 on 2021-08-03 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0004_auto_20210729_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldUnload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mould_id', models.IntegerField()),
                ('mould_name', models.CharField(max_length=200)),
                ('cavity_number', models.CharField(max_length=200)),
                ('clause_1', models.BooleanField()),
                ('clause_2', models.BooleanField()),
                ('clause_3', models.BooleanField()),
                ('clause_4', models.BooleanField()),
                ('clause_5', models.BooleanField()),
                ('clause_6', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreventiveMaintaince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied_for_maitaince', models.DateTimeField(auto_now_add=True)),
                ('date_of_get_back_from_cleaning', models.DateTimeField(null=True)),
                ('comment', models.CharField(max_length=200)),
                ('mould_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mould_pm_history', to='mould.mould')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralClearningArchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied_for_cleaning', models.DateTimeField()),
                ('date_get_back_from_cleaning', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=200)),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mould_gc_history', to='mould.mould')),
            ],
        ),
    ]
