# Generated by Django 3.1.5 on 2021-08-03 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0005_generalclearningarchieve_mouldunload_preventivemaintaince'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouldDailyCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=100)),
                ('date_time_of_update', models.DateTimeField(auto_now_add=True)),
                ('clause_1', models.BooleanField()),
                ('clause_2', models.BooleanField()),
                ('clause_3', models.BooleanField()),
                ('clause_4', models.BooleanField()),
                ('clause_5', models.BooleanField()),
                ('clause_6', models.BooleanField()),
                ('clause_7', models.BooleanField()),
                ('clause_8', models.BooleanField()),
                ('clause_9', models.BooleanField()),
                ('claue_10', models.BooleanField()),
                ('mould_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Machine_Mould', to='mould.mould')),
            ],
        ),
    ]
