# Generated by Django 3.1.5 on 2021-08-03 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mould', '0006_moulddailycheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moulddailycheck',
            old_name='claue_10',
            new_name='clause_10',
        ),
    ]
